import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import supabase from "../../supabase";
import { useEffect, useState } from "react";
import {
  Table,
  Text,
  Thead,
  Tbody,
  Tfoot,
  Tr,
  Th,
  Td,
  TableCaption,
  TableContainer,
  Spinner,
  VStack,
} from "@chakra-ui/react";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [info, setInfo] = useState<any>([]);
  const [inputText, setInputText] = useState<string>("");
  const [returnedData, setReturnedData] = useState<any>({});
  const [errorMessage, setErrorMessage] = useState<string>("");
  const [loading, setLoading] = useState<boolean>(false);

  const loadingState = () => {
    setLoading(true);

    setTimeout(() => setLoading(false), 4000);
  };

  const inputChange = (e: any) => {
    setInputText(() => e.target.value);
  };

  const handleDataChecking = (data: string) => {
    setReturnedData({});
    loadingState();
    for (let i = 0; i < info.length; i++) {
      if (data.toLowerCase() === info[i]["PLATE NUMBER"].toLowerCase()) {
        setReturnedData(() => info[i]);
        setErrorMessage("");
        setInputText("");
        return;
      }
    }
    if (JSON.stringify(returnedData) === "{}") {
      setErrorMessage("No data found.");
    }
  };

  useEffect(() => {
    const getData = async () => {
      setLoading(true);
      try {
        const { data: plateData, error } = await supabase
          .from("Plate Number Data")
          .select("*");

        setInfo(() => plateData);
        setLoading(false);
      } catch (err) {
        console.log(err);
        setLoading(false);
      }
    };

    getData();
  }, []);
  return (
    <>
      <Head>
        <title>APNR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <section className={styles.data_input}>
          <h2>Vehicle Plate Number Data Portal</h2>
          <label htmlFor="data">Enter Plate Number:</label> <br />
          <input
            type="text"
            name="text"
            id="text"
            onChange={inputChange}
            value={inputText}
          />
          <button onClick={() => handleDataChecking(inputText)}>Search</button>
        </section>

        <section className={styles.result}>
          {loading && (
            <VStack
              w="full"
              display="flex"
              justifyContent="center"
              alignItems="center"
            >
              <Spinner size="lg" />
              <Text>Gathering Info...</Text>
            </VStack>
          )}
          {JSON.stringify(returnedData) !== "{}" && !loading && (
            <TableContainer>
              <Table variant="simple" size="lg">
                <Thead>
                  <Tr>
                    <Th>PLATE NUMBER</Th>
                    <Th>VEHICLE NAME</Th>
                    <Th>VEHICLE COLOR</Th>
                    <Th>OWNER NAME</Th>
                    <Th>REG/NO</Th>
                    <Th>REG/DATE</Th>
                  </Tr>
                </Thead>
                <Tbody>
                  <Tr>
                    <Td>{returnedData["PLATE NUMBER"]}</Td>
                    <Td>{returnedData["VEHICLE NAME"]}</Td>
                    <Td>{returnedData["VEHICLE COLOR"]}</Td>
                    <Td>{returnedData["OWNER NAME"]}</Td>
                    <Td>{returnedData["REG/NO"]}</Td>
                    <Td>{returnedData["REG/DATE"]}</Td>
                  </Tr>
                </Tbody>
              </Table>
            </TableContainer>
          )}

          {!loading && <h1>{errorMessage}</h1>}
        </section>
      </main>
    </>
  );
}
